apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: example
        image: docker pull ghcr.io/matelang/java-spring-example:sha256:db5776cd7f28cd2ed4f0a9b4f2a285dbaf3896975deff20ddd64b3d816886041
        ports:
        - containerPort: 80

